name: Spotbugs 

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  spotbugs:
    name: Run spotbugs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17 
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17 
          cache: maven

      - name: Build project
        run: mvn -B clean compile

       # Step 1: Generate report but DO NOT fail build
      - name: Run SpotBugs (Generate SARIF)
        run: |
          mvn -B spotbugs:spotbugs \
            -Dspotbugs.format=sarif \
            -Dspotbugs.outputFile=target/spotbugs.sarif
        continue-on-error: true

      # Step 2: Upload SARIF (always runs)
      - name: Upload SpotBugs SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: target/spotbugs.sarif

      # Step 3: Now fail build if bugs exist
#      - name: Fail if SpotBugs found issues
#        run: mvn -B spotbugs:check

