name: Spotbugs 

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  spotbugs:
    name: Run spotbugs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17 
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17 
          cache: maven

      - name: Build project
        run: mvn -B clean compile

      - name: Run spotbugs
        run: mvn -B spotbugs:spotbugs
        continue-on-error: true

      # Step 2: Download SpotBugs CLI
      - name: Download SpotBugs CLI
        run: |
          wget https://github.com/spotbugs/spotbugs/releases/download/4.8.3/spotbugs-4.8.3.tgz
          tar -xzf spotbugs-4.8.3.tgz

      # Step 3: Convert XML â†’ SARIF using CLI
      - name: Convert to SARIF
        run: |
          spotbugs-4.8.3/bin/spotbugs \
            -sarif \
            -output target/spotbugs.sarif \
            -exitcode \
            target/classes

      - name: Upload SpotBugs SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: target/spotbugs.sarif


#      - name: Upload SpotBugs XML as SARIF
#        uses: anchore/scan-action@v3
#        with:
#          fail-build: false

      # Step 3: Now fail build if bugs exist
#      - name: Fail if SpotBugs found issues
#        run: mvn -B spotbugs:check

