name: Spotbugs 

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  spotbugs:
    name: Run spotbugs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17 
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17 
          cache: maven

      - name: Build project
        run: mvn -B clean compile

      - name: Run spotbugs
        run: mvn -B spotbugs:spotbugs spotbugs:check
        continue-on-error: true

      - name: Debug SARIF
        run: |
          echo "Checking SARIF contents..."
          cat target/spotbugs.sarif | head -n 50

      - name: List target directory
        run: ls -R target

      - name: Upload SpotBugs XML as SARIF
        uses: anchore/scan-action@v3
        with:
          fail-build: false

      # Step 3: Now fail build if bugs exist
#      - name: Fail if SpotBugs found issues
#        run: mvn -B spotbugs:check

